# Generated by Django 4.2.11 on 2024-03-09 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_choice_id_alter_poll_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='polls.question'),
        ),
    ]
